### ISSUE TITLE
spring-boot-app sample is not working

### ISSUE THREAD

**Issue by bvaisakh** [onelogin/onelogin-oidc-java#14]
I pulled the source of this sample and made following changes in app/src/main/resources/application.yml. But the final redirection is failing. Can someone help please?

```
security:
  oauth2:
    client:
      clientId: 954801d0-5753-013a-ed0a-0a3af56838e1200825
      clientSecret: 36574520b9b5e92d376adb1266dd64410d9210b3f54a2f23364e0547b2a01d60
      accessTokenUri: https://<subdomain-name>.onelogin.com/oidc/2/token
      userAuthorizationUri: https://<subdomain-name>.onelogin.com/oidc/2/auth
      tokenName: access_token
      authorizedGrantTypes: authorization_code
      scope: openid,profile,email
    resource:
      userInfoUri: https://<subdomain-name>.onelogin.com/oidc/2/me

server:
  port : 8081
```

![JHsDO](https://user-images.githubusercontent.com/6724706/151301751-eaf121ff-b25f-4ecd-b2e1-25c4602dc712.png)
